//! TRACK H — HNSW access path: recall / filtering / deletes /
//! determinism / edges / incremental / scale.
//!
//! Ground truth is brute force over the same dot-product scores, with
//! the same (score desc, id asc) tie-break the index uses. All data is
//! generated by an in-test LCG — no RNG dependency, every run is
//! bit-identical.
//!
//! The 5000-vector base index is built ONCE (OnceLock) and shared by
//! the read-only suites; the delete suite clones it, the determinism
//! suite rebuilds it from the identical insert sequence.

// `x % n == 0` stays: `is_multiple_of` is stable only since Rust 1.87,
// workspace MSRV is 1.81.
#![allow(clippy::manual_is_multiple_of)]

use std::sync::OnceLock;
use std::time::Instant;

use bruce_core::hnsw::HnswIndex;

const N: usize = 5000;
const D: usize = 64;
const M: usize = 16;
const EF_C: usize = 128;
const DATA_SEED: u64 = 0x5EED_0001;
const QUERY_SEED: u64 = 0x5EED_0002;

// ---------------------------------------------------------------- helpers

/// Deterministic LCG (Knuth MMIX constants).
struct Lcg(u64);

impl Lcg {
    fn new(seed: u64) -> Self {
        Lcg(seed)
    }
    fn next_u64(&mut self) -> u64 {
        self.0 = self
            .0
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1442695040888963407);
        self.0
    }
    /// Uniform in [-1, 1) from the top 24 bits.
    fn next_f32(&mut self) -> f32 {
        ((self.next_u64() >> 40) as f32) / ((1u32 << 23) as f32) - 1.0
    }
}

fn gen_unit_vecs(n: usize, d: usize, seed: u64) -> Vec<Vec<f32>> {
    let mut rng = Lcg::new(seed);
    (0..n)
        .map(|_| {
            let mut v: Vec<f32> = (0..d).map(|_| rng.next_f32()).collect();
            let norm = v.iter().map(|x| x * x).sum::<f32>().sqrt();
            assert!(norm > 0.0);
            for x in v.iter_mut() {
                *x /= norm;
            }
            v
        })
        .collect()
}

fn dot(a: &[f32], b: &[f32]) -> f32 {
    a.iter().zip(b).map(|(x, y)| x * y).sum()
}

/// Brute-force top-k ids over rows whose EXTERNAL id (== row index
/// here) passes `pred`, same tie-break as the index.
fn brute_topk(data: &[Vec<f32>], q: &[f32], k: usize, pred: impl Fn(u32) -> bool) -> Vec<u32> {
    let mut scored: Vec<(f32, u32)> = data
        .iter()
        .enumerate()
        .filter(|(i, _)| pred(*i as u32))
        .map(|(i, v)| (dot(q, v), i as u32))
        .collect();
    scored.sort_by(|a, b| b.0.total_cmp(&a.0).then_with(|| a.1.cmp(&b.1)));
    scored.truncate(k);
    scored.into_iter().map(|(_, i)| i).collect()
}

fn recall(got: &[(u32, f32)], truth: &[u32]) -> f64 {
    if truth.is_empty() {
        return 1.0;
    }
    let hits = got.iter().filter(|(id, _)| truth.contains(id)).count();
    hits as f64 / truth.len() as f64
}

fn assert_sorted_desc(got: &[(u32, f32)]) {
    assert!(
        got.windows(2).all(|w| w[0].1 >= w[1].1),
        "results not sorted by score desc: {got:?}"
    );
}

fn build_base() -> (Vec<Vec<f32>>, HnswIndex) {
    let data = gen_unit_vecs(N, D, DATA_SEED);
    let mut idx = HnswIndex::new(D, M, EF_C);
    for (i, v) in data.iter().enumerate() {
        idx.insert(i as u32, v).unwrap();
    }
    (data, idx)
}

fn base() -> &'static (Vec<Vec<f32>>, HnswIndex) {
    static BASE: OnceLock<(Vec<Vec<f32>>, HnswIndex)> = OnceLock::new();
    BASE.get_or_init(build_base)
}

// ---------------------------------------------------------------- (a) recall

#[test]
fn a_recall_at_10_unfiltered() {
    let (data, idx) = base();
    assert_eq!(idx.len(), N);
    let queries = gen_unit_vecs(100, D, QUERY_SEED);
    let mut total = 0.0;
    for q in &queries {
        let got = idx.search(q, 10, 64, None).unwrap();
        assert_eq!(got.len(), 10);
        assert_sorted_desc(&got);
        total += recall(&got, &brute_topk(data, q, 10, |_| true));
    }
    let r = total / queries.len() as f64;
    println!("[hnsw] (a) recall@10 ef=64 n={N} d={D}: {r:.4}");
    assert!(r >= 0.90, "recall@10 = {r:.4} < 0.90");
}

// ------------------------------------------------- (b) filtered recall + widening

#[test]
fn b_filtered_recall_and_adaptive_widening() {
    let (data, idx) = base();
    let queries = gen_unit_vecs(100, D, QUERY_SEED);

    // 20% selectivity: recall vs brute force over the FILTERED set.
    let filt20 = |id: u32| id % 5 == 0;
    let mut total = 0.0;
    for q in &queries {
        let got = idx.search(q, 10, 64, Some(&filt20)).unwrap();
        assert_eq!(got.len(), 10);
        assert_sorted_desc(&got);
        assert!(
            got.iter().all(|(id, _)| filt20(*id)),
            "filter leaked: {got:?}"
        );
        total += recall(&got, &brute_topk(data, q, 10, filt20));
    }
    let r = total / queries.len() as f64;
    println!("[hnsw] (b) filtered recall@10 (20% selectivity) ef=64: {r:.4}");
    assert!(r >= 0.85, "filtered recall@10 = {r:.4} < 0.85");

    // EXTREME 1% selectivity (50 matches >= k=10): adaptive widening
    // must still deliver k results, all matching.
    let filt1 = |id: u32| id % 100 == 0;
    let n_matches = (0..N as u32).filter(|&i| filt1(i)).count();
    assert!(n_matches >= 10);
    for q in &queries {
        let got = idx.search(q, 10, 64, Some(&filt1)).unwrap();
        assert_eq!(
            got.len(),
            10,
            "adaptive widening failed: {} of {n_matches} matches returned",
            got.len()
        );
        assert!(got.iter().all(|(id, _)| filt1(*id)));
        assert_sorted_desc(&got);
    }
    println!("[hnsw] (b) extreme filter (1% selectivity): k=10 returned for all 100 queries");
}

// ---------------------------------------------------------------- (c) deletes

#[test]
fn c_deletes_tombstones() {
    let (data, idx) = base();
    let mut idx = idx.clone();

    let dead = |id: u32| id % 5 == 3; // 20%
    let mut n_dead = 0usize;
    for id in 0..N as u32 {
        if dead(id) {
            idx.delete(id).unwrap();
            n_dead += 1;
        }
    }
    assert_eq!(idx.len(), N - n_dead);
    let frac = idx.tombstone_fraction();
    assert!((frac - 0.2).abs() < 1e-9, "tombstone_fraction = {frac}");
    // double delete and unknown id are clean errors
    assert!(idx.delete(3).is_err());
    assert!(idx.delete(u32::MAX).is_err());

    let queries = gen_unit_vecs(100, D, QUERY_SEED);
    let mut total = 0.0;
    for q in &queries {
        let got = idx.search(q, 10, 64, None).unwrap();
        assert_eq!(got.len(), 10);
        assert_sorted_desc(&got);
        assert!(
            got.iter().all(|(id, _)| !dead(*id)),
            "tombstoned id in results: {got:?}"
        );
        total += recall(&got, &brute_topk(data, q, 10, |id| !dead(id)));
    }
    let r = total / queries.len() as f64;
    println!("[hnsw] (c) survivor recall@10 after 20% deletes: {r:.4}");
    assert!(r >= 0.85, "survivor recall@10 = {r:.4} < 0.85");
}

// ------------------------------------------------------------ (d) determinism

#[test]
fn d_determinism_identical_builds() {
    let (_, idx1) = base();
    let (_, idx2) = build_base(); // second build, same insert sequence
    let queries = gen_unit_vecs(20, D, QUERY_SEED ^ 0xD00D);
    let filt = |id: u32| id % 3 == 0;
    for q in &queries {
        let a = idx1.search(q, 10, 64, None).unwrap();
        let b = idx2.search(q, 10, 64, None).unwrap();
        assert_eq!(a, b, "unfiltered results differ between identical builds");
        let a = idx1.search(q, 10, 64, Some(&filt)).unwrap();
        let b = idx2.search(q, 10, 64, Some(&filt)).unwrap();
        assert_eq!(a, b, "filtered results differ between identical builds");
    }
    println!("[hnsw] (d) determinism: 20 queries bit-identical across two builds");
}

// ----------------------------------------------------------------- (e) edges

#[test]
fn e_edges() {
    // empty index
    let idx = HnswIndex::new(8, 4, 16);
    assert!(idx.is_empty());
    assert_eq!(idx.len(), 0);
    assert_eq!(idx.tombstone_fraction(), 0.0);
    assert_eq!(idx.search(&[0.0; 8], 5, 16, None).unwrap(), vec![]);

    // dimension mismatches are Errs, not panics
    let mut idx = HnswIndex::new(8, 4, 16);
    assert!(idx.insert(0, &[1.0; 7]).is_err());
    assert!(idx.insert(0, &[1.0; 9]).is_err());
    idx.insert(0, &[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
        .unwrap();
    assert!(idx.search(&[1.0; 7], 5, 16, None).is_err());
    // duplicate id is a clean error
    assert!(idx.insert(0, &[0.0; 8]).is_err());

    // k > live nodes returns ALL live, sorted desc
    let data = gen_unit_vecs(5, 8, 42);
    let mut idx = HnswIndex::new(8, 4, 16);
    for (i, v) in data.iter().enumerate() {
        idx.insert(i as u32, v).unwrap();
    }
    let q = gen_unit_vecs(1, 8, 43).remove(0);
    let got = idx.search(&q, 10, 16, None).unwrap();
    assert_eq!(got.len(), 5);
    assert_sorted_desc(&got);
    let mut ids: Vec<u32> = got.iter().map(|(id, _)| *id).collect();
    ids.sort_unstable();
    assert_eq!(ids, vec![0, 1, 2, 3, 4]);

    // after deleting one, k > live returns the 4 survivors
    idx.delete(2).unwrap();
    let got = idx.search(&q, 10, 16, None).unwrap();
    assert_eq!(got.len(), 4);
    assert!(got.iter().all(|(id, _)| *id != 2));

    // k = 0 is a no-op
    assert_eq!(idx.search(&q, 0, 16, None).unwrap(), vec![]);

    // memory accounting is nonzero and grows
    assert!(idx.memory_bytes() > 0);
}

// ----------------------------------------------------------- (f) incremental

#[test]
fn f_incremental_insert_search_interleaved() {
    let n = 1500;
    let data = gen_unit_vecs(n, D, DATA_SEED ^ 0xF00D);
    let queries = gen_unit_vecs(6, D, QUERY_SEED ^ 0xF00D);
    let mut idx = HnswIndex::new(D, M, 64);
    for (i, v) in data.iter().enumerate() {
        idx.insert(i as u32, v).unwrap();
        if i % 250 == 0 || i == n - 1 {
            for q in &queries {
                let k = 5.min(i + 1);
                let got = idx.search(q, 5, 64, None).unwrap();
                assert_eq!(got.len(), k, "mid-build search at size {}", i + 1);
                assert_sorted_desc(&got);
                assert!(got.iter().all(|(id, _)| (*id as usize) <= i));
                // top-1 is exact mid-build (ef=64 blankets these sizes
                // near the query); deterministic, so never flaky.
                let truth = brute_topk(&data[..=i], q, 1, |_| true);
                assert_eq!(got[0].0, truth[0], "top-1 mismatch at size {}", i + 1);
            }
        }
    }
    assert_eq!(idx.len(), n);
}

// -------------------------------------------------------- scale sanity (ignored)

#[test]
#[ignore = "100k-vector scale sanity; run with --release: cargo test -p bruce-core --release --test hnsw_search -- --ignored --nocapture"]
fn scale_100k() {
    let n = 100_000;
    let data = gen_unit_vecs(n, D, DATA_SEED ^ 0xB16);
    let mut idx = HnswIndex::new(D, M, EF_C);
    let t0 = Instant::now();
    for (i, v) in data.iter().enumerate() {
        idx.insert(i as u32, v).unwrap();
    }
    let build_s = t0.elapsed().as_secs_f64();
    println!(
        "[hnsw] scale: built n={n} d={D} M={M} ef_c={EF_C} in {build_s:.1} s ({:.0} inserts/s), ~{:.0} MiB",
        n as f64 / build_s,
        idx.memory_bytes() as f64 / (1024.0 * 1024.0)
    );

    let queries = gen_unit_vecs(100, D, QUERY_SEED ^ 0xB16);
    let t0 = Instant::now();
    let mut sink = 0usize;
    for q in &queries {
        sink += idx.search(q, 10, 64, None).unwrap().len();
    }
    let per_query_ms = t0.elapsed().as_secs_f64() * 1000.0 / queries.len() as f64;
    assert_eq!(sink, 1000);
    println!("[hnsw] scale: search k=10 ef=64: {per_query_ms:.3} ms/query (single-thread)");

    // spot-check recall on 10 queries against 100k-row brute force,
    // sweeping ef (uniform-random d=64 is the hardest case for graph
    // indexes: neighbor dots concentrate, so ef is the recall knob)
    let truths: Vec<Vec<u32>> = queries
        .iter()
        .take(10)
        .map(|q| brute_topk(&data, q, 10, |_| true))
        .collect();
    for ef in [64usize, 128, 256, 512] {
        let t0 = Instant::now();
        let mut total = 0.0;
        for (q, truth) in queries.iter().take(10).zip(&truths) {
            let got = idx.search(q, 10, ef, None).unwrap();
            total += recall(&got, truth);
        }
        println!(
            "[hnsw] scale: recall@10 ef={ef}: {:.4} ({:.3} ms/query)",
            total / 10.0,
            t0.elapsed().as_secs_f64() * 100.0
        );
    }

    if cfg!(debug_assertions) {
        println!("[hnsw] scale: DEBUG build — 2 ms/query bound not asserted (release-only)");
    } else {
        assert!(
            per_query_ms < 2.0,
            "search too slow: {per_query_ms:.3} ms/query >= 2 ms"
        );
    }
}
