"""Generate the error-bar credibility table.

The natural objection to Section 5 is that an error bar can be had more
cheaply: attach a bootstrap interval to a per-facet truncation, or use
the sampling estimator of the closest published system. This table
answers it with the one number that matters for an interval, its
empirical coverage, at a matched budget of 1000 rows per query.

Read from the result files; nothing here is typed by hand.
"""
from pathlib import Path as _P
_ROOT = _P(__file__).resolve().parent.parent
import json
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
EXP = ROOT / "experiments"
OUT = ROOT / "tab_errorbars.tex"
ORDER = [("imdb", "IMDb"), ("amazon", "Amazon"), ("stackexchange", "StackExch.")]
SHARP, DIFFUSE = 0.02, 0.5
BUDGET = 1000

cov, width = {}, {}
for corp, _ in ORDER:
    b = json.load(open(EXP / "rq4_contract" / f"bootstrap_{corp}.json"))
    for r in b["results"]:
        if r["k"] == BUDGET and r["eps"] in (SHARP, DIFFUSE):
            cov[(r["method"], corp, r["eps"])] = r["ci_coverage"]
            width[(r["method"], corp, r["eps"])] = r["half_width_median"]
            if r["method"] == "perfacet_topk":
                width[("certified", corp, r["eps"])] = r["certified_bound_median"]

    o = json.load(open(EXP / "rq1_coverage" / f"olla_{corp}.json"))
    for r in o["results"]:
        if r["budget"] == BUDGET and r["eps"] in (SHARP, DIFFUSE):
            cov[("olla", corp, r["eps"])] = r["ci_coverage"]
            width[("olla", corp, r["eps"])] = r["half_width_median"]

    # our contract, evaluated on the same cut and the same pairs
    df = pd.read_parquet(EXP / "rq4_contract" /
                         f"bootstrap_per_facet_{corp}.parquet")
    df = df[(df.method == "perfacet_topk") & (df.k == BUDGET)]
    for eps in (SHARP, DIFFUSE):
        sub = df[df.eps == eps]
        cov[("certified", corp, eps)] = float(
            (sub.abs_err <= sub.certified_bound * (1 + 1e-9)).mean())

ROWS = [("perfacet_topk", "per-facet top-$b$, bootstrap"),
        ("perfacet_bayes", "\\quad Bayesian bootstrap"),
        ("olla", "stratified sampling~\\cite{hui2026olla}"),
        ("certified", "certified truncation (ours)")]

body = []
for key, label in ROWS:
    cells = []
    for corp, _ in ORDER:
        for eps in (SHARP, DIFFUSE):
            v = cov.get((key, corp, eps))
            cells.append("--" if v is None else f"{v:.2f}")
    body.append(f"{label} & " + " & ".join(cells) + " \\\\")
    if key == "olla":
        body.append("\\midrule")
body = "\n".join(body)

# the width comparison, computed rather than asserted, because it does
# not go one way: the deterministic bound is narrower where truncation
# is the right plan and wider where it is not
tight = sum(1 for c, _ in ORDER
            if width[("certified", c, SHARP)] < width[("perfacet_topk", c, SHARP)])
# largest advantage among the corpora where the bound IS narrower;
# taking a min here silently reported the corpus where it is wider
_ratios = [width[("perfacet_topk", c, SHARP)] / width[("certified", c, SHARP)]
           for c, _ in ORDER
           if width[("certified", c, SHARP)] < width[("perfacet_topk", c, SHARP)]]
best = max(_ratios)
worst_c = max(ORDER, key=lambda x: width[("certified", x[0], DIFFUSE)]
              / width[("perfacet_topk", x[0], DIFFUSE)])[0]
worst = (width[("certified", worst_c, DIFFUSE)]
         / width[("perfacet_topk", worst_c, DIFFUSE)])
assert all(cov[("certified", c, e)] == 1.0 for c, _ in ORDER
           for e in (SHARP, DIFFUSE)), "the contract did not hold everywhere"

tex = f"""% generated by figures/make_tab_errorbars.py -- do not edit by hand
\\begin{{table}}[t]
\\caption{{Can the error bar be believed? Empirical coverage of a
nominal 95\\% interval, over every (query, facet) pair at a matched
budget of {BUDGET} rows per query. A calibrated interval reads
$0.95$; the resampling intervals instead range from $0.29$ to $1.00$,
and which way they miss flips with the temperature, a parameter the
application sets rather than the system. The deterministic bound of
\\S\\ref{{sec:planner}} is not an estimate and held on every pair. Widths
do not favour one side uniformly: at the sharp setting the bound is
narrower than the bootstrap interval on {tight} of the three corpora
(by up to {best:.0f}$\\times$), and at the diffuse setting it is wider
(by up to {worst:.0f}$\\times$), which is the regime where
\\S\\ref{{sec:eval}} recommends the exact pass rather than any
truncation.}}
\\label{{tab:errorbars}}
\\small
\\setlength{{\\tabcolsep}}{{4pt}}
\\begin{{tabular}}{{lcccccc}}
\\toprule
& \\multicolumn{{2}}{{c}}{{IMDb}} & \\multicolumn{{2}}{{c}}{{Amazon}}
& \\multicolumn{{2}}{{c}}{{StackExch.}} \\\\
\\cmidrule(lr){{2-3}} \\cmidrule(lr){{4-5}} \\cmidrule(lr){{6-7}}
method & sharp & diff. & sharp & diff. & sharp & diff. \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}
\\end{{table}}
"""
OUT.write_text(tex)
print(f"wrote {OUT}")
print(f"  contract held on every pair at both temperatures")
print(f"  bound narrower than bootstrap on {tight}/3 corpora at sharp, "
      f"up to {best:.0f}x; wider at diffuse by up to {worst:.0f}x")
