"""Generate the planner-price table from rq4_contract/results2_*.json.

The interesting question about a certified truncation is not whether
the promise was kept -- execution measures the true omitted mass and
repairs any facet that misses, so it must be -- but what keeping it
costs. This table reports the three stages separately.
"""
from pathlib import Path as _P
_ROOT = _P(__file__).resolve().parent.parent
import json
from pathlib import Path

EXP = Path(str(_ROOT / "experiments") + "/rq4_contract")
OUT = Path(str(_ROOT) + "/tab_planner.tex")
ORDER = [("imdb", "IMDb"), ("stackexchange", "StackExchange"), ("amazon", "Amazon")]

rows, held, samples, scans = [], [], set(), []
for corp, nice in ORDER:
    f = EXP / f"results2_{corp}.json"
    if not f.exists():
        continue
    d = json.load(open(f))
    samples.add(d["sketch_sample"])
    # two budgets per corpus: the tightest and the loosest, which
    # bracket the behaviour the sweep shows monotonically
    show = [d["main"][0], d["main"][-1]]
    for i, r in enumerate(show):
        held.append(r["promise_held"])
        scans.append(r["scan_ms_median"])
        first = f"\\multirow{{{len(show)}}}{{*}}{{{nice}}}" if i == 0 else ""
        rows.append(
            f"{first} & {r['budget_frac']*100:.1f} & {r['budget']:.3g} & "
            f"{r['declined_rate']*100:.0f} & "
            f"{r['frac_facets_repaired']*100:.0f} & "
            f"{r['k_ratio_median']:.1f} & "
            f"{r['candidates_frac_median']*100:.1f} & "
            f"{r['bound_slack_median']:.0f} \\\\")
    rows.append("\\midrule")
body = "\n".join(rows[:-1])
assert all(h == 1.0 for h in held), f"promise not always held: {held}"
sample = samples.pop()

tex = f"""% generated by figures/make_tab_planner.py -- do not edit by hand
\\begin{{table}}[tb]
\\caption{{What the certified truncation costs, at the tightest and
loosest of the four budgets swept. The answer met the budget on all 200
queries per corpus and dropped no facet, so the other columns are the
informative ones. \\emph{{decl.}}: planner declines, the {sample}-row
sketch being unable to resolve the budget. \\emph{{repaired}}: facets
execution re-folded exactly. $k/k^{{*}}$: candidates proposed against
the smallest number that would have sufficed. \\emph{{cand.}}: share of
admitted rows accumulated. \\emph{{slack}}: bound over realised error.}}
\\label{{tab:planner}}
\\small
\\setlength{{\\tabcolsep}}{{4pt}}
\\begin{{tabular}}{{llcccccc}}
\\toprule
& \\multicolumn{{2}}{{c}}{{budget $\\beta$}} & decl. & repaired & & cand. & \\\\
\\cmidrule(lr){{2-3}}
corpus & \\% & abs. & \\% & \\% & $k/k^{{*}}$ & \\% & slack \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}
\\end{{table}}
"""
OUT.write_text(tex)
print(f"wrote {OUT}; promise held on every row; scans {min(scans):.0f}-{max(scans):.0f} ms")
