"""Generate the SQL-forms table from rq2_cost/sql_baselines_*.json.

Three ways to write the operator in SQL, against the fused kernel, on
the same data and the same machine. The table exists because a
comparison against only the naive form would be a straw man.
"""
from pathlib import Path as _P
_ROOT = _P(__file__).resolve().parent.parent
import json
from pathlib import Path

EXP = Path(str(_ROOT / "experiments") + "/rq2_cost")
OUT = Path(str(_ROOT) + "/tab_sql.tex")
d = json.load(open(EXP / "sql_baselines_imdb.json"))
R = {(r["engine"], r["form"], r["eps"]): r for r in d["results"]}
EPS = sorted({r["eps"] for r in d["results"]})
SHOW = [EPS[-1], 0.02, EPS[0]]          # diffuse, working, sharp
LINES = [("postgres", "naive", "PostgreSQL, naive"),
         ("postgres", "stable", "\\quad + max-shift"),
         ("postgres", "guarded", "\\quad + guarded exp"),
         ("duckdb", "naive", "DuckDB, naive"),
         ("duckdb", "stable", "\\quad + max-shift"),
         ("numpy", "reference", "fused single pass")]

rows = []
for eng, form, label in LINES:
    cells = []
    for e in SHOW:
        r = R.get((eng, form, e))
        if r is None:
            cells.append("--"); continue
        if r["ok_rate"] < 1.0:
            cells.append(f"\\textbf{{{r['ok_rate']*100:.0f}\\%}}")
        elif r["n_nonfinite"] > 0:
            cells.append(f"\\textbf{{NaN}}")
        else:
            cells.append(f"{r['ms_median']:.0f}")
    rows.append(f"{label} & " + " & ".join(cells) + " \\\\")
    if form == "guarded":
        rows.append("\\addlinespace")
body = "\n".join(rows)

pg_over = d["errors"].get("postgres/naive", "")
pg_under = d["errors"].get("postgres/stable", "")
# the caption names these two failure modes, so pin them to the data
assert "overflow" in pg_over and "underflow" not in pg_over, pg_over
assert "underflow" in pg_under, pg_under

tex = f"""% generated by figures/make_tab_sql.py -- do not edit by hand
\\begin{{table}}[t]
\\caption{{Median latency in milliseconds for the same aggregate written
three ways in SQL, on {d['n_admitted']:,} admitted rows over
{d['n_facets']} facets, against the fused single pass. A bold
percentage is the share of queries that \\emph{{completed}}. The DuckDB
rows and the fused pass aggregate the same precomputed similarities,
which isolates the aggregation plan; PostgreSQL computes the similarity
itself through the vector extension, sequential scan forced.}}
\\label{{tab:sql}}
\\small
\\begin{{tabular}}{{lccc}}
\\toprule
& diffuse & working & sharp \\\\
form & $\\eps={SHOW[0]:g}$ & $\\eps={SHOW[1]:g}$ & $\\eps={SHOW[2]:g}$ \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}
\\end{{table}}
"""
OUT.write_text(tex)

# The table costs more page than its six numbers are worth, so the text
# quotes them instead. They are still generated, never typed: this file
# defines the macros the prose uses, so a re-measurement propagates.
def _ms(eng, form, e):
    return f"{R[(eng, form, e)]['ms_median']:.0f}"


def _ok(eng, form, e):
    return f"{R[(eng, form, e)]['ok_rate']*100:.0f}"


macros = "\n".join([
    "% generated by figures/make_tab_sql.py -- do not edit by hand",
    f"\\newcommand{{\\sqlPgNaive}}{{{_ms('postgres','naive',0.5)}}}",
    f"\\newcommand{{\\sqlPgShift}}{{{_ms('postgres','stable',0.5)}}}",
    f"\\newcommand{{\\sqlPgGuard}}{{{_ms('postgres','guarded',0.5)}}}",
    f"\\newcommand{{\\sqlPgNaiveOk}}{{{_ok('postgres','naive',EPS[0])}}}",
    f"\\newcommand{{\\sqlPgShiftOk}}{{{_ok('postgres','stable',EPS[0])}}}",
    f"\\newcommand{{\\sqlDuckNaive}}{{{_ms('duckdb','naive',0.5)}}}",
    f"\\newcommand{{\\sqlDuckShift}}{{{_ms('duckdb','stable',0.5)}}}",
    f"\\newcommand{{\\sqlFused}}{{{_ms('numpy','reference',0.5)}}}",
    f"\\newcommand{{\\sqlRows}}{{{d['n_admitted']:,}}}".replace(",", "{,}"),
    "",
])
(OUT.parent / "sql_numbers.tex").write_text(macros)
print(f"wrote {OUT} and sql_numbers.tex")
print(f"  postgres naive:  {pg_over.splitlines()[0]}")
print(f"  postgres stable: {pg_under.splitlines()[0]}")
