"""Concentration table: measured coverage against what a same-sized
uniform random draw would achieve.

Generated from scaling.json so the mechanism claim in the text is tied
to the numbers that support it.
"""
from pathlib import Path as _P
_ROOT = _P(__file__).resolve().parent.parent
import json
from pathlib import Path

S = json.load(open("" + str(_ROOT / "experiments") + "/rq1_coverage/scaling.json"))
NICE = {"amazon": "Amazon", "stackexchange": "StackExchange", "imdb": "IMDb"}
KS = [100, 1000, 10000]
rows = []
for c in ["amazon", "stackexchange", "imdb"]:
    if c not in S["corpora"]:
        continue
    pts = {p["k"]: p for p in S["corpora"][c]["points"]}
    cells = []
    for k in KS:
        p = pts.get(k)
        cells += ([f"{p['coverage']*100:.0f}", f"{p['uniform_reference']*100:.0f}",
                   f"{p['concentration_gap_pp']:.0f}"] if p else ["--"] * 3)
    rows.append(f"{NICE[c]} & " + " & ".join(cells) + " \\\\")
body = "\n".join(rows)
tex = f"""% generated by figures/make_tab_concentration.py -- do not edit by hand
\\begin{{table}}[t]
\\caption{{Where the missing facets go. \\emph{{sim}} is measured coverage
under similarity retrieval; \\emph{{unif}} is the coverage a uniform
random draw of the same $k$ would achieve, computed from the facet size
distribution alone with no semantics in it; \\emph{{gap}} is the
difference in percentage points. The gap is what concentration costs,
and it is the part of the shortfall that a larger retrieval budget buys
back only slowly.}}
\\label{{tab:concentration}}
\\small
\\setlength{{\\tabcolsep}}{{4pt}}
\\begin{{tabular}}{{lccccccccc}}
\\toprule
& \\multicolumn{{3}}{{c}}{{$k=100$}} & \\multicolumn{{3}}{{c}}{{$k=1000$}}
& \\multicolumn{{3}}{{c}}{{$k=10{{,}}000$}} \\\\
\\cmidrule(lr){{2-4}} \\cmidrule(lr){{5-7}} \\cmidrule(lr){{8-10}}
corpus & sim & unif & gap & sim & unif & gap & sim & unif & gap \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}
\\end{{table}}
"""
(_ROOT / "tab_concentration.tex").write_text(tex)
print("wrote tab_concentration.tex")
