"""Corpus statistics table, generated from the corpora themselves.

Standard in an IR paper, and load-bearing here: the facet size
distribution is the reason a facet can be lost, so the skew column is
part of the argument rather than housekeeping.
"""
from pathlib import Path as _P
_ROOT = _P(__file__).resolve().parent.parent
import json
from pathlib import Path
import numpy as np, pandas as pd

ROOT = Path(str(_ROOT / "experiments") + "/corpora")
SPEC = [("amazon", "Amazon Reviews", "product category", "star rating",
         2015.0, "review year $\\ge$ 2015"),
        ("stackexchange", "StackExchange", "site", "answer score",
         3.0, "question score $\\ge$ 3"),
        ("imdb", "IMDb", "primary genre", "user rating",
         2000.0, "release year $\\ge$ 2000")]
missing = [d for d, *_ in SPEC if not (ROOT / d / "corpus.parquet").exists()]
if missing:
    raise SystemExit(
        "This table is built from the corpora themselves, and the corpora\n"
        "are not shipped with the artifact (6.5 GB of parquet and\n"
        f"embeddings). Missing: {', '.join(missing)}.\n\n"
        "Rebuild them first -- see REPRODUCE.md step 2:\n"
        "    cd experiments/corpora && python3 build_amazon.py && ...\n\n"
        "Every other generator, and verify_claims.py, reads result files\n"
        "and runs without the corpora.")

rows = []
for d, nice, facet, value, thr, pred in SPEC:
    df = pd.read_parquet(ROOT / d / "corpus.parquet",
                         columns=["facet", "filter_num", "value"])
    meta = json.loads((ROOT / d / "meta.json").read_text())
    adm = df.filter_num.values >= thr
    sizes = df.facet.values[adm]
    c = pd.Series(sizes).value_counts().values
    rows.append(dict(nice=nice, n=len(df), adm=int(adm.sum()), g=len(c),
                     smallest=int(c.min()), median=int(np.median(c)),
                     largest=int(c.max()), skew=c.max() / c.min(),
                     facet=facet, value=value, pred=pred,
                     sel=float(adm.mean())))

body = "\n".join(
    f"{r['nice']} & {r['n']/1e6:.2f}M & {r['adm']/1e6:.2f}M "
    f"({r['sel']*100:.0f}\\%) & {r['g']} & "
    f"{r['smallest']:,} & {r['largest']:,} "
    "\\\\".replace(",", "{,}") for r in rows)
imdb_none = int(pd.read_parquet(ROOT / "imdb" / "corpus.parquet",
                                columns=["facet", "filter_num"])
                .query("filter_num >= 2000").facet.value_counts().iloc[0])
imdb_none_tex = f"{imdb_none:,}".replace(",", "{,}")
predlist = ", ".join(f"{r['pred']} ({r['nice'].split()[0]})" for r in rows)
legend = "; ".join(f"{r['nice']}: facet = {r['facet']}, value = {r['value']}"
                   for r in rows)

tex = f"""% generated by figures/make_tab_corpora.py -- do not edit by hand
\\begin{{table}}[t]
\\caption{{Corpora. \\emph{{Admitted}} is the number of items surviving the
query's exact predicate. The facet size distribution is part of the
argument rather than housekeeping: a facet holding a thousandth of the
corpus is one a fixed-size retrieval is unlikely to reach at all.
{legend}; predicates are {predlist}. Every item carries exactly one
facet label: an IMDb title takes its primary genre rather than being
exploded over its genres, and the {imdb_none_tex} admitted titles
recording no genre form their own facet rather than being dropped,
which is why IMDb's largest facet leads its second by a wide margin.}}
\\label{{tab:corpora}}
\\small
\\setlength{{\\tabcolsep}}{{4pt}}
\\begin{{tabular}}{{lrrrrr}}
\\toprule
& & & & \\multicolumn{{2}}{{c}}{{facet size}} \\\\
\\cmidrule(lr){{5-6}}
corpus & items & admitted & facets & smallest & largest \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}
\\end{{table}}
"""
out = Path(str(_ROOT) + "/tab_corpora.tex")
out.write_text(tex)
print(f"wrote {out}")
for r in rows:
    print(f"  {r['nice']:<16}{r['n']:>9,}{r['adm']:>10,}{r['g']:>5}"
          f"{r['smallest']:>8,}{r['largest']:>9,}{r['skew']:>7.0f}x")
